stages:
  - test
  - upload-report

test:
  stage: test
  image: node:10.15.3
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - report/
  only:
    - master

upload-report:
  stage: upload-report
  image: katalonstudio/report-uploader:0.0.7.11
  script:
    - uploader.sh
  variables:
    PROJECT_ID: 50236
    TYPE: junit
    REPORT_PATH: report
  dependencies:
    - test
  only:
    - master


