name: Build Report Uploader Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '10'

      - name: Run test
        run: npm install && npm test

      - name: Katalon Report Uploader
        uses: katalon-studio/report-uploader@v0.0.7.11
        env:
          PASSWORD: ${{ secrets.KATALON_API_KEY }}
          PROJECT_ID: 50236
          TYPE: junit
          REPORT_PATH: ${{ github.workspace }}/report

